INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Football', 'Premier League', 20, 20, 400);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Basketball', 'NBA', 30, 30, 450);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Tennis', 'ATP Tour', 50, 50, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Cricket', 'IPL', 10, 10, 200);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Rugby', 'Super Rugby', 15, 15, 300);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Netball', 'Netball Premier League', 12, 12, 180);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Badminton', 'BWF World Tour', 60, 60, 120);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Swimming', 'FINA World Championships', 40, 40, 80);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Running', 'World Athletics Series', 0, 0, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Cycling', 'UCI World Tour', 30, 30, 150);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Ice Hockey', 'NHL', 32, 32, 640);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Baseball', 'MLB', 30, 30, 900);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Golf', 'PGA Tour', 100, 100, 200);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Table Tennis', 'ITTF World Tour', 80, 80, 160);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Volleyball', 'FIVB World League', 24, 24, 288);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Handball', 'EHF Champions League', 16, 16, 192);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Wrestling', 'UWW World Championship', 50, 50, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Gymnastics', 'FIG World Championships', 40, 40, 80);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Skiing', 'FIS World Cup', 60, 60, 120);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Surfing', 'World Surf League', 30, 30, 60);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Boxing', 'WBC', 200, 200, 400);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('MMA', 'UFC', 100, 100, 200);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Fencing', 'FIE World Cup', 50, 50, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Archery', 'World Archery Tour', 40, 40, 80);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Shooting', 'ISSF World Cup', 30, 30, 60);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Rowing', 'World Rowing Championships', 20, 20, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Canoeing', 'ICF World Championships', 25, 25, 75);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Sailing', 'World Sailing Cup', 35, 35, 140);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Horse Racing', 'Derby Series', 50, 50, 200);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Motorsport', 'Formula 1', 10, 10, 200);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Triathlon', 'World Triathlon Series', 20, 20, 60);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Racing', 'Tour de France', 22, 22, 176);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Surf Lifesaving', 'ISLS', 30, 30, 120);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Climbing', 'IFSC World Cup', 40, 40, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Skateboarding', 'Street League', 25, 25, 50);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Snowboarding', 'FIS Snowboard World Cup', 30, 30, 60);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Ice Skating', 'ISU Grand Prix', 20, 20, 40);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Karate', 'WKF World Championship', 50, 50, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Judo', 'IJF World Tour', 40, 40, 80);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Taekwondo', 'WT World Championship', 30, 30, 60);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Weightlifting', 'IWF World Championship', 25, 25, 50);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Powerlifting', 'IPF World Championship', 20, 20, 40);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Rowing Indoor', 'World Indoor Rowing', 15, 15, 45);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Dance Sport', 'WDSF World Championship', 10, 10, 50);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Bowling', 'PBA Tour', 12, 12, 48);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Lacrosse', 'PLL', 8, 8, 120);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Softball', 'WBSC', 16, 16, 192);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Beach Volleyball', 'FIVB World Tour', 24, 24, 144);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Futsal', 'FIFA Futsal World Cup', 32, 32, 192);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Pickleball', 'APP Tour', 20, 20, 100);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('Chess', 'FIDE World Championship', 0, 0, 50);
INSERT INTO dbo.Sports (SportName, LeagueName, TeamsCount, ManagersCount, AthletesCount) VALUES ('eSports', 'League of Legends Championship', 22, 22, 110);