INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('City FC', 'Premier League', 3);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('United FC', 'Premier League', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Rovers', 'Premier League', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Lakers', 'NBA', 4);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Heat', 'NBA', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Bulls', 'NBA', 3);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Aces', 'ATP Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Smashers', 'ATP Tour', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Servers', 'ATP Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Warriors', 'IPL', 3);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Strikers', 'IPL', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Titans', 'IPL', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Blues', 'Super Rugby', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Chiefs', 'Super Rugby', 3);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Hurricanes', 'Super Rugby', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Stars', 'Netball Premier League', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Magic', 'Netball Premier League', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Pulse', 'Netball Premier League', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Shuttlers', 'BWF World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Flyers', 'BWF World Tour', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Birdies', 'BWF World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Dolphins', 'FINA World Championships', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Sharks', 'FINA World Championships', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Seals', 'FINA World Championships', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Sprinters', 'World Athletics Series', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Dashers', 'World Athletics Series', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Fleet', 'World Athletics Series', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Riders', 'UCI World Tour', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Spinners', 'UCI World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Chain', 'UCI World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('City United', 'Premier League', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Lakers Elite', 'NBA', 3);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Aces Pro', 'ATP Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Warriors Prime', 'IPL', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Blues United', 'Super Rugby', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Magic Stars', 'Netball Premier League', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Shuttlers Pro', 'BWF World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Dolphins Elite', 'FINA World Championships', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Sprinters Fast', 'World Athletics Series', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Riders Pro', 'UCI World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Spinners Elite', 'UCI World Tour', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Chain Masters', 'UCI World Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('United Legends', 'Premier League', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Heatwave', 'NBA', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Smash Kings', 'ATP Tour', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Titans Force', 'IPL', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Hurricanes Storm', 'Super Rugby', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Stars Magic', 'Netball Premier League', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Flyers Pro', 'BWF World Tour', 2);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Sharks Elite', 'FINA World Championships', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Dashers Prime', 'World Athletics Series', 1);
INSERT INTO dbo.Team (TeamName, LeagueName, InjuredPlayerCount) VALUES ('Riders Masters', 'UCI World Tour', 2);